### ISSUE TITLE
Protocol button is gigantic

### ISSUE THREAD

**Issue by sagangwee** [sagangwee/safespace#77]

**Comment by gz2ca** [comment]
lol they want it bigger

**Comment by sagangwee** [comment]
Well it's also off the screen and not aligned properly

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: gz2ca notifications@github.com Date: 10/25/16  8:57 AM  (GMT-08:00) To: sagangwee/safespace safespace@noreply.github.com Cc: Sagang Wee sagangwee@yahoo.com, Author author@noreply.github.com Subject: Re: [sagangwee/safespace] Protocol button is gigantic (#77) 
lol they want it bigger

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sagangwee/safespace","title":"sagangwee/safespace","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sagangwee/safespace"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gz2ca in #77: lol they want it bigger\r\n"}],"action":{"name":"View Issue","url":"https://github.com/sagangwee/safespace/issues/77#issuecomment-256078021"}}}

**Comment by gz2ca** [comment]
Haven't finished it fixing it yet hahaha, will get to it today
